In [1]:
# import de librairies
import numpy as np
import pandas as pd
import string as str
#afficher toutes les lignes
# pd.set_option('display.max_row', 20)

In [2]:
# repertoire de l'utilisateur
%pwd

'C:\\Users\\Cissé-LENOVO\\Desktop\\Openclassrooms\\Data analyst\\Projet 3  Réalisez une étude de santé publique\\Jupyter\\P3_cisse_yaya\\P3_01_codereponses'

# Sources:

# Le lien de téléchargement est:
http://www.fao.org/faostat/fr/#data/FBS

# J'ai téléchargé 5 fichiers csv:
1. fr_population.csv, ce fichier contient la population mondiale par pays
dimension: 175 lignes × 15 colonnes

15 colonnes: Code Domaine, Domaine, Code zone, Zone, Code Élément, Élément, Code Produit, Produit, Code année, 	Année, Unité, Valeur, Symbole, Description du Symbole, population_en_millier

2. fr_animaux.csv, il contient les produits d'origine animale de chaque pays
dimension: 36908 lignes × 15 colonnes

15 colonnes: Code Domaine, Domaine,	Code zone, Zone, Code Élément, Élément,	Code Produit, Produit, Code année 	Année, Unité, Valeur, Symbole, Description du Symbole, source

3. fr_vegetaux.csv, il contient les produits d'origine végétale de chaque pays
dimension: 104011 lignes × 15 colonnes

15 colonnes: Code Domaine, Domaine, Code zone, Zone, Code Élément, 	Élément, 	Code Produit,	Produit, 	Code année, 	Année, 	Unité, 	Valeur, 	Symbole, 	Description du Symbole, 	source

4. fr_céréales.csv, il contient les produits céréaliers de chaque pays 
dimension: 891 lignes × 15 colonnes

15 colonnes: Code Domaine, 	Domaine, 	Code zone, 	Zone, 	Code Élément, 	Élément, 	Code Produit, 	Produit ,	Code année, 	Année, 	Unité, 	Valeur, 	Symbole, 	Description du , 	is_cereal

5. fr_sousalimentation.csv, il contient le nombre de personnes sous-alimentées de chaque pays
dimension: 1020 lignes × 15 colonnes

15 colonnes: Code Domaine, 	Domaine, 	Code zone, 	Zone, 	Code Élément, 	Élément, 	Code Produit, 	Produit, 	Code année, 	Année, 	Unité, 	Valeur, 	Symbole, 	Description du Symbole, 	Note

# Le répertoire contenant ces fichiers se trouve dans:

'C:\\Users\\Cissé-LENOVO\\Desktop\\Openclassrooms\\Data analyst\\Projet 3  Réalisez une étude de santé publique\\Jupyter\\P3_01_codereponses'

# Question 1 : donnez le résultat de votre calcul pour l'année 2013.
Parmi les documents sur les Bilans alimentaires que vous avez téléchargés, il y a des informations redondantes. En effet, pour un pays donné, certaines de ces informations peuvent se calculer à partir d'autres :

    Production 
    Importations
    Exportations 
    Variation de stock 
    Disponibilité intérieure 
    Semences 
    Pertes 
    Nourriture, aussi appelée Disponibilité alimentaire 
    Aliments pour animaux 
    Traitement
    Autres utilisations

In [3]:
# importation du fichier csv contenant la population depuis le repertoire
population = pd.read_csv('fr_population.csv', sep=',')
# Calcul de la population totale avec laa redondance
population_totale = population['Valeur'].sum()*1000
population_totale

8413993000

In [4]:
population

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,236,Venezuela (République bolivarienne du),511,Population totale,2501,Population,2013,2013,1000 personnes,30405,NaN,Donnée officielle
171,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,237,Viet Nam,511,Population totale,2501,Population,2013,2013,1000 personnes,91680,NaN,Donnée officielle
172,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,249,Yémen,511,Population totale,2501,Population,2013,2013,1000 personnes,24407,NaN,Donnée officielle
173,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,251,Zambie,511,Population totale,2501,Population,2013,2013,1000 personnes,14539,NaN,Donnée officielle
174,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,511,Population totale,2501,Population,2013,2013,1000 personnes,14150,NaN,Donnée officielle

In [5]:
# ajouter une nouvelle colonne population_en_millier à population 
# et convertissons cette derniere en million: population_en_millier multipliée par 1000
population = population.assign(population_en_millier = population['Valeur']*1000)

# Création du nouveau dataframe sans la redondance
population_sans_chine = population[population.Zone != 'Chine']

# Population mondiale sans redondance: La grande Chine est supprimée, on trouvera desormais avec les 
population_totale = population_sans_chine[['population_en_millier']].sum()
population_totale

population_en_millier    6997326000
dtype: int64

In [6]:
population_sans_chine

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,population_en_millier
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,511,Population totale,2501,Population,2013,2013,1000 personnes,30552,NaN,Donnée officielle,30552000
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,202,Afrique du Sud,511,Population totale,2501,Population,2013,2013,1000 personnes,52776,NaN,Donnée officielle,52776000
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,3,Albanie,511,Population totale,2501,Population,2013,2013,1000 personnes,3173,NaN,Donnée officielle,3173000
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,4,Algérie,511,Population totale,2501,Population,2013,2013,1000 personnes,39208,NaN,Donnée officielle,39208000
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,79,Allemagne,511,Population totale,2501,Population,2013,2013,1000 personnes,82727,NaN,Donnée officielle,82727000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,236,Venezuela (République bolivarienne du),511,Population totale,2501,Population,2013,2013,1000 personnes,30405,NaN,Donnée officielle,30405000
171,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,237,Viet Nam,511,Population totale,2501,Population,2013,2013,1000 personnes,91680,NaN,Donnée officielle,91680000
172,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,249,Yémen,511,Population totale,2501,Population,2013,2013,1000 personnes,24407,NaN,Donnée officielle,24407000
173,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,251,Zambie,511,Population totale,2501,Population,2013,2013,1000 personnes,14539,NaN,Donnée officielle,14539000
174,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,511,Population totale,2501,Population,2013,2013,1000 personnes,14150,NaN,Donnée officielle,14150000

# Question 2 : Identifiez ces redondances, en donnant votre réponse sous forme de formule mathématique (pas besoin de coder ici :soleil: ). 

C'est une équation à 3 termes de type (a_1 + a2 + [...] = b_1 + b_2 + [...] = c_1 + c_2 + [...]\) ) faisant intervenir chacune des 11 quantités

1 : Production + importations - exportations + variations des stocks

2 : Disponibilité intérieure

3 : Disponibilité alimentaire + Aliments pour animaux + Semences + Traitement + Autres Utilisations + Pertes

# 1. Production + importations + variations des stocks = disponibilité Alimentaire
# 2. Production + importations + variations des stocks = exportation + disponibilité intérieure.
# 3. Disponibilité alimentaire + Aliments pour animaux + Semences + Traitement+ Autres Utilisations + Pertes = disponibilité intérieure
# 4.disponibilité intérieure = Production + importations - exportations + variations des stocks

Or Production + importations + variations des stocks = Disponibilité intérieure + exportations = disponibilité alimentaire

De ce fait, on a l’égalité entre 1 et 4

# Production + importations - exportations + variations des stocks =  
# Disponibilité alimentaire + Aliments pour animaux + Semences + Traitement + Autres Utilisations + Pertes = 
# Disponibilité intérieure

# Question 3 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.

## Vous ferez cela à partir de ces informations
     Population de chaque pays ;
     Disponibilité alimentaire donnée pour chaque produit et pour 
     chaque pays en kcal/personne/jour.
     Disponibilité alimentaire en protéines donnée pour chaque      
     produit et pour chaque pays en g/personne/jour.

In [7]:
# Importer le fichier fr_animaux.csv
animaux = pd.read_csv('fr_animaux.csv', sep=',')
animaux = animaux.assign(source = 'animale')
animaux = animaux[animaux.Zone != 'Chine']

# Importer le fichier fr_vegetaux.csv
vegetaux = pd.read_csv('fr_vegetaux.csv', sep=',')
vegetaux = vegetaux.assign(source = 'végétale')
vegetaux = vegetaux[vegetaux.Zone != 'Chine']

# Union de 2 dataframes animaux et vegetaux
animaux_vegetaux = pd.concat([animaux, vegetaux])
#animaux_vegetaux =animaux_vegetaux[['Code zone','Zone', 'Code Produit','Produit','Code année','Élément', 'Valeur', 'source']]
animaux_vegetaux

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées,animale
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées,animale
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées,animale
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées,animale
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée,animale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104866,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,végétale
104867,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,végétale
104868,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.00,Fc,Donnée calculée,végétale
104869,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée,végétale
104870,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2013,2013,g/personne/jour,0.03,Fc,Donnée calculée,végétale

In [8]:
# Essayons d'obtenir la nourriture de chaque pays et de chaque produit 
nourriture = animaux_vegetaux[animaux_vegetaux.Élément == 'Nourriture']
nourriture = nourriture.assign(nourriture = nourriture['Valeur']*1000*1000)
nourriture = nourriture[['Code zone','Zone', 'Produit', 'Élément', 'nourriture', 'source']]
nourriture

,Code zone,Zone,Produit,Élément,nourriture,source
3,2,Afghanistan,Viande de Bovins,Nourriture,140000000.0,animale
10,2,Afghanistan,Viande d'Ovins/Caprins,Nourriture,150000000.0,animale
18,2,Afghanistan,Viande de Volailles,Nourriture,75000000.0,animale
26,2,Afghanistan,"Viande, Autre",Nourriture,12000000.0,animale
33,2,Afghanistan,Abats Comestible,Nourriture,53000000.0,animale
...,...,...,...,...,...,...
104826,181,Zimbabwe,Vin,Nourriture,4000000.0,végétale
104834,181,Zimbabwe,Bière,Nourriture,292000000.0,végétale
104842,181,Zimbabwe,Boissons Fermentés,Nourriture,148000000.0,végétale
104851,181,Zimbabwe,Boissons Alcooliques,Nourriture,73000000.0,végétale
104863,181,Zimbabwe,Aliments pour enfants,Nourriture,0.0,végétale

In [9]:
# Création d'un dataframe avec 2 colonnes zone et population en millier
population_sans_chine = population_sans_chine[['Zone', 'population_en_millier']]

# Calculons la disponibilité alimentaire en quantité (kg/personne/an) de chaque pays et de chaque produit 
dispo_alim_kg = animaux_vegetaux[animaux_vegetaux.Élément == 'Disponibilité alimentaire en quantité (kg/personne/an)']
dispo_alim_kg = dispo_alim_kg.assign(dispo_alim_kg_personne = dispo_alim_kg['Valeur'])
dispo_alim_kg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source,dispo_alim_kg_personne
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée,animale,4.59
11,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2732,Viande d'Ovins/Caprins,2013,2013,kg,4.92,Fc,Donnée calculée,animale,4.92
19,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2013,2013,kg,2.45,Fc,Donnée calculée,animale,2.45
27,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2735,"Viande, Autre",2013,2013,kg,0.38,Fc,Donnée calculée,animale,0.38
34,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2736,Abats Comestible,2013,2013,kg,1.72,Fc,Donnée calculée,animale,1.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104827,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2655,Vin,2013,2013,kg,0.27,Fc,Donnée calculée,végétale,0.27
104835,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2656,Bière,2013,2013,kg,20.63,Fc,Donnée calculée,végétale,20.63
104843,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2657,Boissons Fermentés,2013,2013,kg,10.44,Fc,Donnée calculée,végétale,10.44
104852,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2658,Boissons Alcooliques,2013,2013,kg,5.15,Fc,Donnée calculée,végétale,5.15
104864,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2680,Aliments pour enfants,2013,2013,kg,0.00,Fc,Donnée calculée,végétale,0.00

In [10]:

# joindre le dataframe dispo_alim_kg au dataframe population_sans_chine sur la clé Zone avec la jointure à gauche
dispo_alim_kg = dispo_alim_kg.merge(population_sans_chine, how ='left', on = 'Zone')
dispo_alim_kg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source,dispo_alim_kg_personne,population_en_millier
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée,animale,4.59,30552000
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2732,Viande d'Ovins/Caprins,2013,2013,kg,4.92,Fc,Donnée calculée,animale,4.92,30552000
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2013,2013,kg,2.45,Fc,Donnée calculée,animale,2.45,30552000
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2735,"Viande, Autre",2013,2013,kg,0.38,Fc,Donnée calculée,animale,0.38,30552000
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2736,Abats Comestible,2013,2013,kg,1.72,Fc,Donnée calculée,animale,1.72,30552000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14010,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2655,Vin,2013,2013,kg,0.27,Fc,Donnée calculée,végétale,0.27,14150000
14011,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2656,Bière,2013,2013,kg,20.63,Fc,Donnée calculée,végétale,20.63,14150000
14012,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2657,Boissons Fermentés,2013,2013,kg,10.44,Fc,Donnée calculée,végétale,10.44,14150000
14013,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2658,Boissons Alcooliques,2013,2013,kg,5.15,Fc,Donnée calculée,végétale,5.15,14150000
14014,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2680,Aliments pour enfants,2013,2013,kg,0.00,Fc,Donnée calculée,végétale,0.00,14150000

In [11]:

# création de la colonne dispo_alim_kg d'un produit pour la population d'un pays donné 
dispo_alim_kg = dispo_alim_kg.assign(dispo_alim_kg = dispo_alim_kg['dispo_alim_kg_personne']*dispo_alim_kg['population_en_millier'])
dispo_alim_kg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source,dispo_alim_kg_personne,population_en_millier,dispo_alim_kg
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée,animale,4.59,30552000,140233680.0
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2732,Viande d'Ovins/Caprins,2013,2013,kg,4.92,Fc,Donnée calculée,animale,4.92,30552000,150315840.0
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2734,Viande de Volailles,2013,2013,kg,2.45,Fc,Donnée calculée,animale,2.45,30552000,74852400.0
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2735,"Viande, Autre",2013,2013,kg,0.38,Fc,Donnée calculée,animale,0.38,30552000,11609760.0
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2736,Abats Comestible,2013,2013,kg,1.72,Fc,Donnée calculée,animale,1.72,30552000,52549440.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14010,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2655,Vin,2013,2013,kg,0.27,Fc,Donnée calculée,végétale,0.27,14150000,3820500.0
14011,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2656,Bière,2013,2013,kg,20.63,Fc,Donnée calculée,végétale,20.63,14150000,291914500.0
14012,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2657,Boissons Fermentés,2013,2013,kg,10.44,Fc,Donnée calculée,végétale,10.44,14150000,147726000.0
14013,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2658,Boissons Alcooliques,2013,2013,kg,5.15,Fc,Donnée calculée,végétale,5.15,14150000,72872500.0
14014,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2680,Aliments pour enfants,2013,2013,kg,0.00,Fc,Donnée calculée,végétale,0.00,14150000,0.0

In [12]:
# creation du dataframe de disponibilite alimentaire kcal
dispo_alim_kcal = animaux_vegetaux[animaux_vegetaux.Élément == 'Disponibilité alimentaire (Kcal/personne/jour)']

# jointure de dispo_alim_kcal et population_sans_chine à gauche et sur la clé Zone
dispo_alim_kcal = dispo_alim_kcal.merge(population_sans_chine, how='left', on = 'Zone')

#création de la colonnne dispo_alim_kcal qui représente la dispo_alim_kcal de chaque produit par an par pays
dispo_alim_kcal = dispo_alim_kcal.assign(dispo_alim_kcal = dispo_alim_kcal['Valeur'] * dispo_alim_kcal['population_en_millier'] * 365)
dispo_alim_kcal

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source,population_en_millier,dispo_alim_kcal
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2731,Viande de Bovins,2013,2013,Kcal/personne/jour,27.0,Fc,Donnée calculée,animale,30552000,3.010900e+11
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2732,Viande d'Ovins/Caprins,2013,2013,Kcal/personne/jour,31.0,Fc,Donnée calculée,animale,30552000,3.456959e+11
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2734,Viande de Volailles,2013,2013,Kcal/personne/jour,9.0,Fc,Donnée calculée,animale,30552000,1.003633e+11
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2735,"Viande, Autre",2013,2013,Kcal/personne/jour,1.0,Fc,Donnée calculée,animale,30552000,1.115148e+10
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,664,Disponibilité alimentaire (Kcal/personne/jour),2736,Abats Comestible,2013,2013,Kcal/personne/jour,5.0,Fc,Donnée calculée,animale,30552000,5.575740e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14236,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2656,Bière,2013,2013,Kcal/personne/jour,24.0,Fc,Donnée calculée,végétale,14150000,1.239540e+11
14237,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2657,Boissons Fermentés,2013,2013,Kcal/personne/jour,10.0,Fc,Donnée calculée,végétale,14150000,5.164750e+10
14238,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2658,Boissons Alcooliques,2013,2013,Kcal/personne/jour,42.0,Fc,Donnée calculée,végétale,14150000,2.169195e+11
14239,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2680,Aliments pour enfants,2013,2013,Kcal/personne/jour,0.0,Fc,Donnée calculée,végétale,14150000,0.000000e+00
14240,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2013,2013,Kcal/personne/jour,2.0,Fc,Donnée calculée,végétale,14150000,1.032950e+10

In [13]:
# Affichage de la disponibilité de protéines en quantité (g/personne/jour)
# calcul de la disponibilité de protéines en quantité (g/personne/jour) de chaque pays et de chaque produit
dispo_prot_g = animaux_vegetaux[animaux_vegetaux.Élément == 'Disponibilité de protéines en quantité (g/personne/jour)']

# Jointure à gauche entre dispo_prot_g et population_sans_chine sur la clé Zone
dispo_prot_g = dispo_prot_g.merge(population_sans_chine, how = 'left', on ='Zone')
# convertir la disponibilité alimentaire en kg/personne/an
dispo_prot_kg = dispo_prot_g.assign(dispo_prot_kg = (dispo_prot_g['Valeur']* 0.001 * dispo_prot_g['population_en_millier']*365))
dispo_prot_kg

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,source,population_en_millier,dispo_prot_kg
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2731,Viande de Bovins,2013,2013,g/personne/jour,1.89,Fc,Donnée calculée,animale,30552000,21076297.2
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2732,Viande d'Ovins/Caprins,2013,2013,g/personne/jour,1.91,Fc,Donnée calculée,animale,30552000,21299326.8
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2734,Viande de Volailles,2013,2013,g/personne/jour,0.87,Fc,Donnée calculée,animale,30552000,9701787.6
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2735,"Viande, Autre",2013,2013,g/personne/jour,0.17,Fc,Donnée calculée,animale,30552000,1895751.6
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,674,Disponibilité de protéines en quantité (g/pers...,2736,Abats Comestible,2013,2013,g/personne/jour,0.77,Fc,Donnée calculée,animale,30552000,8586639.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11556,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2645,"Épices, Autres",2013,2013,g/personne/jour,0.02,Fc,Donnée calculée,végétale,14150000,103295.0
11557,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2656,Bière,2013,2013,g/personne/jour,0.28,Fc,Donnée calculée,végétale,14150000,1446130.0
11558,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2657,Boissons Fermentés,2013,2013,g/personne/jour,0.13,Fc,Donnée calculée,végétale,14150000,671417.5
11559,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2680,Aliments pour enfants,2013,2013,g/personne/jour,0.00,Fc,Donnée calculée,végétale,14150000,0.0
11560,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2013,2013,g/personne/jour,0.07,Fc,Donnée calculée,végétale,14150000,361532.5

# Question 4 : A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg. Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la valeur calorique d'un oeuf.

In [14]:
# Creation du ratio: jointure à gauche entre dispo_alim_kcal et dispo_alim_kg sur les 2 clés Zone et Produit
ratio = dispo_alim_kcal.merge(dispo_alim_kg, on=['Zone', 'Produit'], how='left')
# Jointure entre ratio et dispo_prot_kg à gauche sur les clés Zone et Produit
ratio = ratio.merge(dispo_prot_kg,on=['Zone', 'Produit'], how='left')
# Sélection des colonnes ci-dessous
ratio = ratio[['Code zone','Zone','Produit','Élément', 'dispo_alim_kcal', 'dispo_prot_kg', 'dispo_alim_kg', 'source']]
# Calcul du ratio energie_sur_poids
ratio = ratio.assign(energie_sur_poids = ratio['dispo_alim_kcal'] / ratio['dispo_alim_kg'])
# Remplaçons les cellules en NAN par 0
ratio['energie_sur_poids'].fillna(0, inplace=True)
# affichage des 5 premieres lignes
ratio.head(5)

,Code zone,Zone,Produit,Élément,dispo_alim_kcal,dispo_prot_kg,dispo_alim_kg,source,energie_sur_poids
0,2.0,Afghanistan,Viande de Bovins,Disponibilité de protéines en quantité (g/pers...,3.010900e+11,21076297.2,140233680.0,animale,2147.058824
1,2.0,Afghanistan,Viande d'Ovins/Caprins,Disponibilité de protéines en quantité (g/pers...,3.456959e+11,21299326.8,150315840.0,animale,2299.796748
2,2.0,Afghanistan,Viande de Volailles,Disponibilité de protéines en quantité (g/pers...,1.003633e+11,9701787.6,74852400.0,animale,1340.816327
3,2.0,Afghanistan,"Viande, Autre",Disponibilité de protéines en quantité (g/pers...,1.115148e+10,1895751.6,11609760.0,animale,960.526316
4,2.0,Afghanistan,Abats Comestible,Disponibilité de protéines en quantité (g/pers...,5.575740e+10,8586639.6,52549440.0,animale,1061.046512

In [15]:
# comparer à une valeur de référence de l'oeuf sur wiki
# Sur wikipedia œuf moyen de 100 g : 147 kcal calories => ratio :1470 

# selectionner les oeufs parmi les produits
oeuf = ratio[ratio.Produit == 'Oeufs']
# Choix des oeufs de la france
oeuf = oeuf[oeuf.Zone == 'France']
# projection sur les colonnes ci-dessous
oeuf[['Zone', 'Produit', 'energie_sur_poids']]

        Zone Produit  energie_sur_poids
1280  France   Oeufs        1417.745621

# En suivant la même méthodologie, calculez également le pourcentage de protéines de chaque produit (pour chaque pays). Ce pourcentage est obtenu en calculant le ratio "poids de protéines/poids total" (attention aux unités utilisées)

In [16]:
# Calcul du ratio poids de protéines sur poids sur poids total
ratio = ratio.assign(proteine_sur_poids = ratio['dispo_prot_kg'] / ratio['dispo_alim_kg'])
ratio['proteine_sur_poids'].fillna(0, inplace=True)
ratio

,Code zone,Zone,Produit,Élément,dispo_alim_kcal,dispo_prot_kg,dispo_alim_kg,source,energie_sur_poids,proteine_sur_poids
0,2.0,Afghanistan,Viande de Bovins,Disponibilité de protéines en quantité (g/pers...,3.010900e+11,21076297.2,140233680.0,animale,2147.058824,0.150294
1,2.0,Afghanistan,Viande d'Ovins/Caprins,Disponibilité de protéines en quantité (g/pers...,3.456959e+11,21299326.8,150315840.0,animale,2299.796748,0.141697
2,2.0,Afghanistan,Viande de Volailles,Disponibilité de protéines en quantité (g/pers...,1.003633e+11,9701787.6,74852400.0,animale,1340.816327,0.129612
3,2.0,Afghanistan,"Viande, Autre",Disponibilité de protéines en quantité (g/pers...,1.115148e+10,1895751.6,11609760.0,animale,960.526316,0.163289
4,2.0,Afghanistan,Abats Comestible,Disponibilité de protéines en quantité (g/pers...,5.575740e+10,8586639.6,52549440.0,animale,1061.046512,0.163401
...,...,...,...,...,...,...,...,...,...,...
14236,181.0,Zimbabwe,Bière,Disponibilité de protéines en quantité (g/pers...,1.239540e+11,1446130.0,291914500.0,végétale,424.624333,0.004954
14237,181.0,Zimbabwe,Boissons Fermentés,Disponibilité de protéines en quantité (g/pers...,5.164750e+10,671417.5,147726000.0,végétale,349.616858,0.004545
14238,NaN,Zimbabwe,Boissons Alcooliques,NaN,2.169195e+11,NaN,72872500.0,NaN,2976.699029,0.000000
14239,181.0,Zimbabwe,Aliments pour enfants,Disponibilité de protéines en quantité (g/pers...,0.000000e+00,0.0,0.0,végétale,0.000000,0.000000
14240,181.0,Zimbabwe,Miscellanees,Disponibilité de protéines en quantité (g/pers...,1.032950e+10,361532.5,NaN,végétale,0.000000,0.000000

# Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids.
# Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays. Vous créerez donc une nouvelle table grâce à une agrégation. Attention à bien retirer les valeurs égales à 0 afin de ne pas fausser le calcul de la moyenne.

In [17]:
# drop a row if any of the values in the row equal zero
#Remplaçons par 0, les valeurs inf et nan
ratio['proteine_sur_poids'].replace([0, np.inf], np.nan, inplace = True)
ratio['energie_sur_poids'].replace([0, np.inf], np.nan, inplace = True)

ratio

,Code zone,Zone,Produit,Élément,dispo_alim_kcal,dispo_prot_kg,dispo_alim_kg,source,energie_sur_poids,proteine_sur_poids
0,2.0,Afghanistan,Viande de Bovins,Disponibilité de protéines en quantité (g/pers...,3.010900e+11,21076297.2,140233680.0,animale,2147.058824,0.150294
1,2.0,Afghanistan,Viande d'Ovins/Caprins,Disponibilité de protéines en quantité (g/pers...,3.456959e+11,21299326.8,150315840.0,animale,2299.796748,0.141697
2,2.0,Afghanistan,Viande de Volailles,Disponibilité de protéines en quantité (g/pers...,1.003633e+11,9701787.6,74852400.0,animale,1340.816327,0.129612
3,2.0,Afghanistan,"Viande, Autre",Disponibilité de protéines en quantité (g/pers...,1.115148e+10,1895751.6,11609760.0,animale,960.526316,0.163289
4,2.0,Afghanistan,Abats Comestible,Disponibilité de protéines en quantité (g/pers...,5.575740e+10,8586639.6,52549440.0,animale,1061.046512,0.163401
...,...,...,...,...,...,...,...,...,...,...
14236,181.0,Zimbabwe,Bière,Disponibilité de protéines en quantité (g/pers...,1.239540e+11,1446130.0,291914500.0,végétale,424.624333,0.004954
14237,181.0,Zimbabwe,Boissons Fermentés,Disponibilité de protéines en quantité (g/pers...,5.164750e+10,671417.5,147726000.0,végétale,349.616858,0.004545
14238,NaN,Zimbabwe,Boissons Alcooliques,NaN,2.169195e+11,NaN,72872500.0,NaN,2976.699029,NaN
14239,181.0,Zimbabwe,Aliments pour enfants,Disponibilité de protéines en quantité (g/pers...,0.000000e+00,0.0,0.0,végétale,NaN,NaN
14240,181.0,Zimbabwe,Miscellanees,Disponibilité de protéines en quantité (g/pers...,1.032950e+10,361532.5,NaN,végétale,NaN,NaN

# On agrège les lignes des tables energie_sur_poids et proteine_sur_poids, c'est-à-dire que l'on forme des agrégats pour effectuer sur eux une opération la moyenne qui porte sur plusieurs lignes des tables energie_sur_poids et proteine_sur_poids.

In [18]:
# Calcul du ratio moyen
ratio['proteine_sur_poids'].fillna(0, inplace=True)
# Sélectionnons les colonnes Produit, energie_sur_poids et proteine_sur_poids à travers regroupement par produit
# puis calculons la moyenne
ratio_moyen = ratio[[ 'Produit', 'energie_sur_poids', 'proteine_sur_poids']].groupby('Produit').mean().reset_index()
# une colonne agrégation réduit les nbr de lignes
#ratio_moyen.head(6)
ratio_moyen

                     Produit  energie_sur_poids  proteine_sur_poids
0           Abats Comestible        1132.473774        1.763090e-01
1            Agrumes, Autres         256.962548        1.364427e-03
2      Aliments pour enfants        3826.952046        1.274796e-01
3                     Ananas         442.588355        1.982703e-03
4   Animaux Aquatiques Autre         618.224052        1.247880e-02
..                       ...                ...                 ...
92          Viande de Suides        2522.656620        9.716165e-02
93       Viande de Volailles        1301.168956        1.262002e-01
94             Viande, Autre        1372.485525        1.630952e-01
95                       Vin         757.879849        4.201057e-07
96            Épices, Autres        3587.285792        1.018267e-01

[97 rows x 3 columns]

In [19]:
# Calcul du ratio_1 moyen
# Sélectionnons les colonnes Produit, energie_sur_poids à travers regroupement par produit
# puis calculons la moyenne
ratio_moyen_1 = ratio.groupby('Produit').mean().reset_index()
# une colonne agrégation réduit les nbr de lignes
ratio_moyen_1

,Produit,Code zone,dispo_alim_kcal,dispo_prot_kg,dispo_alim_kg,energie_sur_poids,proteine_sur_poids
0,Abats Comestible,125.431034,9.907831e+10,1.609122e+07,9.001586e+07,1132.473774,1.763090e-01
1,"Agrumes, Autres",127.076271,1.606344e+10,4.411723e+05,7.375555e+07,256.962548,1.364427e-03
2,Aliments pour enfants,123.888199,1.736034e+10,7.338130e+05,4.783092e+06,3826.952046,1.274796e-01
3,Ananas,125.194631,4.212772e+10,3.684822e+05,1.236961e+08,442.588355,1.982703e-03
4,Animaux Aquatiques Autre,119.570370,4.082917e+09,3.398951e+05,9.307772e+06,618.224052,1.247880e-02
...,...,...,...,...,...,...,...
92,Viande de Suides,123.738095,1.880341e+12,7.060198e+07,6.633026e+08,2522.656620,9.716165e-02
93,Viande de Volailles,125.431034,8.617331e+11,7.570735e+07,6.027775e+08,1301.168956,1.262002e-01
94,"Viande, Autre",125.431034,4.611526e+10,6.951264e+06,3.925711e+07,1372.485525,1.630952e-01
95,Vin,130.041667,9.398455e+10,4.030208e+01,1.360476e+08,757.879849,4.201057e-07
96,"Épices, Autres",124.194118,9.809293e+10,3.243216e+06,2.978110e+07,3587.285792,1.018267e-01

In [20]:
# Calcul du ratio_2 moyen
# Sélectionnons les colonnes Produit, proteine_sur_poids à travers regroupement par produit
# puis calculons la moyenne
ratio_moyen_2 = ratio[['Produit', 'proteine_sur_poids']].groupby('Produit').mean().reset_index()
# une colonne agrégation réduit les nbr de lignes
ratio_moyen_2

                     Produit  proteine_sur_poids
0           Abats Comestible        1.763090e-01
1            Agrumes, Autres        1.364427e-03
2      Aliments pour enfants        1.274796e-01
3                     Ananas        1.982703e-03
4   Animaux Aquatiques Autre        1.247880e-02
..                       ...                 ...
92          Viande de Suides        9.716165e-02
93       Viande de Volailles        1.262002e-01
94             Viande, Autre        1.630952e-01
95                       Vin        4.201057e-07
96            Épices, Autres        1.018267e-01

[97 rows x 2 columns]

In [21]:
#affichage des 20 premiers ratio energie sur poids 
decroissant = ratio_moyen_1.sort_values(by =['energie_sur_poids'], ascending = False)
decroissant = decroissant.head(20)
decroissant

,Produit,Code zone,dispo_alim_kcal,dispo_prot_kg,dispo_alim_kg,energie_sur_poids,proteine_sur_poids
44,Huiles de Foie de Poisso,123.420690,6.902377e+08,0.000000e+00,8.723862e+04,11809.003531,0.000000
42,Huile de Sésame,123.833333,4.695227e+10,0.000000e+00,5.610706e+06,10146.064841,0.000000
34,Huile d'Olive,33.000000,1.439530e+11,0.000000e+00,1.639012e+07,9292.674322,0.000000
37,Huile de Germe de Maïs,97.000000,1.206377e+11,3.993465e+04,1.386736e+07,9257.130389,0.000097
41,Huile de Son de Riz,110.000000,3.739515e+11,4.640756e+05,4.718876e+07,9206.134101,0.000362
36,Huile de Colza&Moutarde,128.689655,7.098785e+11,1.984054e+05,8.167592e+07,9149.964104,0.000554
33,Huile d'Arachide,149.666667,2.053493e+11,4.503289e+03,2.441160e+07,9118.262843,0.000062
43,Huile de Tournesol,129.707317,5.444558e+11,2.098927e+05,6.290756e+07,9027.791629,0.000329
39,Huile de Palmistes,132.826087,1.814025e+11,3.761039e+04,2.094076e+07,9012.117711,0.000343
32,Huile Graines de Coton,143.269231,3.119827e+11,1.232924e+05,3.589605e+07,8972.360166,0.000357
35,Huile de Coco,134.833333,1.264866e+11,6.104151e+04,1.486541e+07,8932.572320,0.000694
45,Huiles de Poissons,125.786164,3.822005e+09,0.000000e+00,4.324336e+05,8917.431319,0.000000
40,Huile de Soja,126.731707,1.244761e+12,7.247237e+05,1.440128e+08,8900.180815,0.000477
38,Huile de Palme,124.688889,1.087285e+12,3.142523e+05,1.245969e+08,8791.217534,0.001187
31,Huil Plantes Oleif Autr,123.802721,8.594252e+10,3.857879e+04,1.047755e+07,8720.818117,0.004524
29,Graisses Animales Crue,123.886905,4.281835e+11,3.842249e+05,6.017116e+07,7579.278844,0.013136
9,"Beurre, Ghee",127.114458,4.365135e+11,3.820043e+05,5.593092e+07,7470.526350,0.005968
86,Sésame,125.162162,6.691236e+10,2.254281e+06,1.214810e+07,6136.984310,0.148802
5,Arachides Decortiquees,126.380952,3.866596e+11,1.671491e+07,7.278402e+07,5705.476348,0.246433
62,Palmistes,129.416667,1.797913e+09,0.000000e+00,2.616471e+05,5475.000000,0.000000

In [22]:
# trier le ratio des oeufs par ordre decroissant
decroissant_proteine = ratio_moyen_2.sort_values(by =['proteine_sur_poids'], ascending = False)
decroissant_proteine = decroissant_proteine.head(20)
decroissant_proteine

                     Produit  proteine_sur_poids
5     Arachides Decortiquees            0.246433
49       Légumineuses Autres            0.207302
69                      Pois            0.203854
30                  Haricots            0.202259
80                      Soja            0.201447
0           Abats Comestible            0.176309
94             Viande, Autre            0.163095
86                    Sésame            0.148802
91          Viande de Bovins            0.144611
89    Viande d'Ovins/Caprins            0.136573
2      Aliments pour enfants            0.127480
93       Viande de Volailles            0.126200
72       Poissons Pelagiques            0.120599
57                     Oeufs            0.106961
71   Poissons Marins, Autres            0.104971
70        Poissons Eau Douce            0.103353
96            Épices, Autres            0.101827
15              Cephalopodes            0.101114
92          Viande de Suides            0.097162
68  Plantes Oleiferes, Autre            0.094640

# Question 6 : Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.

In [23]:
# creation de dataframe de la disponibilite intérieure par la restriction sur la Disponibilité intérieure
dispo_interieure = vegetaux[vegetaux.Élément == "Disponibilité intérieure"]
# Creer une nouvelle colonne dispo_interieure 
dispo_interieure = dispo_interieure.assign(dispo_interieure = dispo_interieure['Valeur']*1000*1000)
dispo_interieure = dispo_interieure[['Zone', 'Code zone', 'Code Produit','Élément', 'Produit', 'dispo_interieure', 'source']]
dispo_interieure = dispo_interieure[dispo_interieure['dispo_interieure']>0]

# Jointure de proteine_sur_poids et dispo_interieure sur Zone et Produit à gauche 

dp = dispo_interieure.merge(ratio,  how="left", on =['Zone', 'Produit', 'source'])
dp = dp[['Zone', 'Produit', 'source', 'energie_sur_poids','proteine_sur_poids', 'dispo_interieure','dispo_prot_kg']]

# création de la colonne dispo_interieure_kcal
dp = dp.assign(dispo_interieure_kcal = dp['energie_sur_poids'] * dp['dispo_interieure'])

# création de la colonne dispo_interieure_kg
dp = dp.assign(dispo_interieure_kg = dp['proteine_sur_poids'] * dp['dispo_interieure'])
dp.fillna(0, inplace=True)
dp

,Zone,Produit,source,energie_sur_poids,proteine_sur_poids,dispo_interieure,dispo_prot_kg,dispo_interieure_kcal,dispo_interieure_kg
0,Afghanistan,Blé,végétale,3118.548337,0.084080,5.992000e+09,411601126.8,1.868634e+13,5.038078e+08
1,Afghanistan,Riz (Eq Blanchi),végétale,3723.950796,0.071310,4.610000e+08,30108996.0,1.716741e+12,3.287377e+07
2,Afghanistan,Orge,végétale,3250.000000,0.098750,5.240000e+08,8809669.2,1.703000e+12,5.174500e+07
3,Afghanistan,Maïs,végétale,3066.000000,0.081760,3.130000e+08,6244828.8,9.596580e+11,2.559088e+07
4,Afghanistan,Millet,végétale,2737.500000,0.073000,1.300000e+07,892118.4,3.558750e+10,9.490000e+05
...,...,...,...,...,...,...,...,...,...
8495,Zimbabwe,"Épices, Autres",végétale,6083.333333,0.121667,1.000000e+06,103295.0,6.083333e+09,1.216667e+05
8496,Zimbabwe,Vin,végétale,0.000000,0.000000,4.000000e+06,0.0,0.000000e+00,0.000000e+00
8497,Zimbabwe,Bière,végétale,424.624333,0.004954,2.920000e+08,1446130.0,1.239903e+11,1.446554e+06
8498,Zimbabwe,Boissons Fermentés,végétale,349.616858,0.004545,1.480000e+08,671417.5,5.174330e+10,6.726628e+05
8499,Zimbabwe,Boissons Alcooliques,végétale,0.000000,0.000000,7.300000e+07,0.0,0.000000e+00,0.000000e+00

In [24]:
#disponibilité interieure mondiale en kcal
dispo_interieure_kcal_mondiale = dp[dp.source=='végétale']
#convertir la disponibilité intérieure kcal mondiale en entier
dispo_interieure_kcal_mondiale = int(dp['dispo_interieure_kcal'].sum())
dispo_interieure_kcal_mondiale

10800980105545260

In [25]:
#disponibilité interieure mondiale de proteines en kg
dispo_interieure_kg_mondiale = dp[dp.source=='végétale']
#convertir la disponibilité intérieure mondiale de proteines en kg en entier
dispo_interieure_kg_mondiale = int(dp['dispo_interieure_kg'].sum())
dispo_interieure_kg_mondiale

292658754747

# Question 7 : Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale!!!

In [26]:
# poids moyen 62 kg
besoin_prot = 62 * 0.8 * 365 / 1000

# 2200 kcal / personne / jour 
# calories recommandées par an
besoin_kcal = 2200 * 365


# population mondiale qui pourrait etre nourrie par les calories 
population_kcal = int(dispo_interieure_kcal_mondiale / besoin_kcal)
population_kcal

13450784689

In [27]:
# pourcentage de la disponibilite interieure en kcal de produits vegetaux qui pourraient nourrir la population
pourcentage_population_kcal = (population_kcal/ population_totale)*100
pourcentage_population_kcal

population_en_millier    192.227498
dtype: float64

In [28]:
# population mondiale qui pourrait etre nourrie par les kg de proteines 
population_kg = dispo_interieure_kg_mondiale/besoin_prot
population_kg

16165419506.573133

In [29]:

# pourcentage de la population mondiale qui pourrait etre nourrie par les kg de proteines 
pourcentage_population_kg = (population_kg/population_totale)
pourcentage_population_kg*100

population_en_millier    231.022815
dtype: float64

# Question 8 : Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [30]:
# disponibilité alimentaire en produits végétaux
dispo_alim_vegetaux = dp[dp.source == 'végétale']
dispo_alim_vegetaux

,Zone,Produit,source,energie_sur_poids,proteine_sur_poids,dispo_interieure,dispo_prot_kg,dispo_interieure_kcal,dispo_interieure_kg
0,Afghanistan,Blé,végétale,3118.548337,0.084080,5.992000e+09,411601126.8,1.868634e+13,5.038078e+08
1,Afghanistan,Riz (Eq Blanchi),végétale,3723.950796,0.071310,4.610000e+08,30108996.0,1.716741e+12,3.287377e+07
2,Afghanistan,Orge,végétale,3250.000000,0.098750,5.240000e+08,8809669.2,1.703000e+12,5.174500e+07
3,Afghanistan,Maïs,végétale,3066.000000,0.081760,3.130000e+08,6244828.8,9.596580e+11,2.559088e+07
4,Afghanistan,Millet,végétale,2737.500000,0.073000,1.300000e+07,892118.4,3.558750e+10,9.490000e+05
...,...,...,...,...,...,...,...,...,...
8495,Zimbabwe,"Épices, Autres",végétale,6083.333333,0.121667,1.000000e+06,103295.0,6.083333e+09,1.216667e+05
8496,Zimbabwe,Vin,végétale,0.000000,0.000000,4.000000e+06,0.0,0.000000e+00,0.000000e+00
8497,Zimbabwe,Bière,végétale,424.624333,0.004954,2.920000e+08,1446130.0,1.239903e+11,1.446554e+06
8498,Zimbabwe,Boissons Fermentés,végétale,349.616858,0.004545,1.480000e+08,671417.5,5.174330e+10,6.726628e+05
8499,Zimbabwe,Boissons Alcooliques,végétale,0.000000,0.000000,7.300000e+07,0.0,0.000000e+00,0.000000e+00

In [31]:
# création du dataframe nourriture à partir du filtre des nourritures sur vegetaux
nourriture = vegetaux[vegetaux.Élément == 'Nourriture']
# convertir les nourritures en kg 
nourriture = nourriture.assign(valeurs_nour = nourriture['Valeur']*1000*1000)
# création du dataframe Pertes à partir du filtre des pertes sur vegetaux

pertes = vegetaux[vegetaux.Élément == 'Pertes']
# renommée de la colonne Valeur en valeur_pertes
pertes = pertes.rename(columns={"Valeur": "valeur_pertes"})
pertes = pertes.assign(valeurs_pertes = pertes['valeur_pertes']*1000*1000)

# création du dataframe nourriture des animaux à partir du filtre des nourriture_animaux sur vegetaux
nourriture_animaux = vegetaux[vegetaux.Élément == 'Aliments pour animaux']
# renommée de la colonne Valeur en valeur_nourriture
nourriture_animaux = nourriture_animaux.rename(columns={"Valeur": "valeur_nour_anim"})

# convertir les nourriture en kg 
nourriture_animaux = nourriture_animaux.assign(valeurs_nour_anim = nourriture_animaux['valeur_nour_anim']*1000*1000)

# Jointure entre dispo_alim_kg et nourriture sur Zone et Produit, cette dernière est jointe au dataframe pertes sur Zone et Produit 
dispo_pertes_nourriture = nourriture.merge(nourriture_animaux, on = ['Zone','Produit']).merge(pertes, on = ['Zone','Produit'])

#affichage des colonnes ciblées
dispo_pertes_nourriture = dispo_pertes_nourriture[['Zone','Code Produit', 'Produit', 'valeurs_nour', 'valeurs_pertes', 'valeurs_nour_anim']]

#insérer une colonne dispo_pertes_nourriture 
dispo_pertes_nourriture = dispo_pertes_nourriture.assign(dispo_pertes_nourriture = dispo_pertes_nourriture['valeurs_nour']+dispo_pertes_nourriture['valeurs_pertes']+dispo_pertes_nourriture['valeurs_nour_anim'])
dispo_pertes_nourriture_2 = dispo_pertes_nourriture[['Zone','Code Produit','Produit', 'valeurs_nour', 'valeurs_nour_anim']]
dispo_pertes_nourriture

,Zone,Code Produit,Produit,valeurs_nour,valeurs_pertes,valeurs_nour_anim,dispo_pertes_nourriture
0,Afghanistan,2513,Orge,8.900000e+07,52000000.0,360000000.0,5.010000e+08
1,Afghanistan,2514,Maïs,7.600000e+07,31000000.0,200000000.0,3.070000e+08
2,Afghanistan,2549,Légumineuses Autres,7.400000e+07,3000000.0,4000000.0,8.100000e+07
3,Afrique du Sud,2511,Blé,3.174000e+09,74000000.0,37000000.0,3.285000e+09
4,Afrique du Sud,2513,Orge,5.000000e+06,7000000.0,19000000.0,3.100000e+07
...,...,...,...,...,...,...,...
1191,Zambie,2517,Millet,9.000000e+06,2000000.0,2000000.0,1.300000e+07
1192,Zambie,2605,"Légumes, Autres",3.060000e+08,35000000.0,0.0,3.410000e+08
1193,Zimbabwe,2513,Orge,3.000000e+06,4000000.0,3000000.0,1.000000e+07
1194,Zimbabwe,2514,Maïs,1.326000e+09,71000000.0,50000000.0,1.447000e+09
1195,Zimbabwe,2518,Sorgho,5.700000e+07,5000000.0,1000000.0,6.300000e+07

In [32]:
# Jointure entra le dataframe dispo_alim_vegetaux et dispo_pertes_nourriture sur les clés Zone et Produit
dispo_pertes_nour_veg = dispo_pertes_nourriture.merge(dispo_alim_vegetaux, how='left', on =['Zone', 'Produit'])
dispo_pertes_nour_veg

,Zone,Code Produit,Produit,valeurs_nour,valeurs_pertes,valeurs_nour_anim,dispo_pertes_nourriture,source,energie_sur_poids,proteine_sur_poids,dispo_interieure,dispo_prot_kg,dispo_interieure_kcal,dispo_interieure_kg
0,Afghanistan,2513,Orge,8.900000e+07,52000000.0,360000000.0,5.010000e+08,végétale,3250.000000,0.098750,5.240000e+08,8.809669e+06,1.703000e+12,5.174500e+07
1,Afghanistan,2514,Maïs,7.600000e+07,31000000.0,200000000.0,3.070000e+08,végétale,3066.000000,0.081760,3.130000e+08,6.244829e+06,9.596580e+11,2.559088e+07
2,Afghanistan,2549,Légumineuses Autres,7.400000e+07,3000000.0,4000000.0,8.100000e+07,végétale,3440.573770,0.233361,8.600000e+07,1.739631e+07,2.958893e+11,2.006902e+07
3,Afrique du Sud,2511,Blé,3.174000e+09,74000000.0,37000000.0,3.285000e+09,végétale,2986.529187,0.093481,3.316000e+09,2.966539e+08,9.903331e+12,3.099823e+08
4,Afrique du Sud,2513,Orge,5.000000e+06,7000000.0,19000000.0,3.100000e+07,végétale,4055.555556,0.040556,5.090000e+08,1.926324e+05,2.064278e+12,2.064278e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,Zambie,2517,Millet,9.000000e+06,2000000.0,2000000.0,1.300000e+07,végétale,2433.333333,0.079083,2.400000e+07,6.898756e+05,5.840000e+10,1.898000e+06
1192,Zambie,2605,"Légumes, Autres",3.060000e+08,35000000.0,0.0,3.410000e+08,végétale,259.724858,0.014545,3.370000e+08,4.457657e+06,8.752728e+10,4.901528e+06
1193,Zimbabwe,2513,Orge,3.000000e+06,4000000.0,3000000.0,1.000000e+07,végétale,3041.666667,0.060833,6.600000e+07,2.065900e+05,2.007500e+11,4.015000e+06
1194,Zimbabwe,2514,Maïs,1.326000e+09,71000000.0,50000000.0,1.447000e+09,végétale,2894.908198,0.076249,1.480000e+09,1.010742e+08,4.284464e+12,1.128492e+08
1195,Zimbabwe,2518,Sorgho,5.700000e+07,5000000.0,1000000.0,6.300000e+07,végétale,2966.748768,0.090800,9.300000e+07,5.216398e+06,2.759076e+11,8.444446e+06

In [33]:
# Affichage des colonnes ciblées de dispo_alim_vegetaux
dispo_alim_vegetaux = dispo_alim_vegetaux[['Zone', 'Produit', 'energie_sur_poids', 'proteine_sur_poids']]
dispo_alim_vegetaux

             Zone               Produit  energie_sur_poids  proteine_sur_poids
0     Afghanistan                   Blé        3118.548337            0.084080
1     Afghanistan      Riz (Eq Blanchi)        3723.950796            0.071310
2     Afghanistan                  Orge        3250.000000            0.098750
3     Afghanistan                  Maïs        3066.000000            0.081760
4     Afghanistan                Millet        2737.500000            0.073000
...           ...                   ...                ...                 ...
8495     Zimbabwe        Épices, Autres        6083.333333            0.121667
8496     Zimbabwe                   Vin           0.000000            0.000000
8497     Zimbabwe                 Bière         424.624333            0.004954
8498     Zimbabwe    Boissons Fermentés         349.616858            0.004545
8499     Zimbabwe  Boissons Alcooliques           0.000000            0.000000

[8500 rows x 4 columns]

In [34]:
# disponibilité alimentaire + pertes + nourriture totale 
dispo_pertes_nourriture_totale = dispo_pertes_nour_veg[['dispo_pertes_nourriture']].sum()
dispo_pertes_nourriture_totale

dispo_pertes_nourriture    3.186610e+12
dtype: float64

In [35]:
# Créons la nouvelle colonne dispo_pertes_nour_kcal
dispo_pertes_nourriture_kcal = dispo_pertes_nour_veg.assign(dispo_pertes_nour_kcal= dispo_pertes_nour_veg['energie_sur_poids']*dispo_pertes_nour_veg['dispo_pertes_nourriture'])

# Cherchons l'energie issue de la somme de la disponibilité alimentaire, de la nourriture et des pertes pour la population mondiale
dispo_pertes_nourriture_kcal_tot = dispo_pertes_nourriture_kcal['dispo_pertes_nour_kcal'].sum()/besoin_kcal
dispo_pertes_nourriture_kcal_tot

7584983771.870665

In [36]:
# pourcentage de la population nourris par la disponibilite alim kcal+ perte + nourriture
dispo_pertes_nourriture_kcal_tot/population_totale*100

population_en_millier    108.398319
dtype: float64

In [37]:
# Créons la nouvelle colonne dispo_pertes_nour_prot
dispo_pertes_nourriture_proteine = dispo_pertes_nour_veg.assign(dispo_pertes_nour_prot= dispo_pertes_nour_veg['proteine_sur_poids']*dispo_pertes_nour_veg['dispo_pertes_nourriture'])
# Cherchons les proteines issus de la somme de la disponibilité alimentaire, de la nourriture et des pertes pour la population mondiale
dispo_pertes_nourriture_proteine = dispo_pertes_nourriture_proteine['dispo_pertes_nour_prot'].sum()/besoin_prot
dispo_pertes_nourriture_proteine

8895426335.865847

In [38]:
# Pourcentage des personnes nourries par les proteines 
dispo_pertes_nourriture_proteine/population_totale*100

population_en_millier    127.126081
dtype: float64

# Question 9 : Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.

In [39]:
# Calculons le nombre d'humains qui pourraient etre nourris avec la disponibilité alimentaire mondiale
# En termes de calories, cherchons d'abord la disponibilité alimentaire mondiale en kcal
dispo_alim_kcal_totale = ratio['dispo_alim_kcal'].sum()
dispo_alim_kcal_totale

7363883420185000.0

In [40]:
# Ensuite la population qui pourraient etre nourris par ces calories
int(dispo_alim_kcal_totale/besoin_kcal)

9170465031

In [41]:
#le pourcentage de personnes nourries par ces calories
dispo_alim_kcal_totale/besoin_kcal/population_totale*100

population_en_millier    131.056707
dtype: float64

In [42]:
# Calculons le nombre d'humains qui pourraient etre nourris avec la disponibilité alimentaire mondiale
# En termes de proteines, cherchons d'abord la disponibilité alimentaire mondiale en kg de proteine
dispo_prot_kg_totale = ratio['dispo_prot_kg'].sum()

# Ensuite la population qui pourraient etre nourris par ces proteines
dispo_prot_kg_totale/besoin_prot
# 9,7 milliards

11448253428.830647

In [43]:
#le pourcentage de personnes nourries par ces proteines
dispo_prot_kg_totale/besoin_prot/population_totale*100

population_en_millier    163.608976
dtype: float64

# Question 10 : A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

In [44]:
# importons le fichier qui concerne la sous-nutrition
sous_alim = pd.read_csv('fr_sousalimentation.csv', sep=',')
# remplaçons les valeurs NAN en 0
#sous_alim = sous_alim.dropna(how='all')
sous_alim

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,6.6,F,Estimation FAO,NaN
1016,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,7.2,F,Estimation FAO,NaN
1017,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,7.8,F,Estimation FAO,NaN
1018,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,8.2,F,Estimation FAO,NaN
1019,FS,Données de la sécurité alimentaire,181,Zimbabwe,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,8.5,F,Estimation FAO,NaN

In [45]:
# Filtrer le dataframe avec une année 2016-2018
sous_alim_2013 = sous_alim[sous_alim.Année == '2012-2014']
# créons la colonne pop_sous_alim
sous_alim_2013 = sous_alim_2013.assign(pop_sous_alim = sous_alim_2013[['Valeur']]*1)
sous_alim_2013 = sous_alim_2013[sous_alim_2013.Zone != 'Chine']
# Convertir la colonne valeur de sous_alim_2018 en valeur numérique
sous_alim_2013['pop_sous_alim'] = pd.to_numeric(sous_alim_2013.pop_sous_alim, errors='coerce')
# calcul de La population sous alimentée mondiale à convertir en millions
pop_sous_alim_mondiale = sous_alim_2013['pop_sous_alim'].sum()*1000000
pop_sous_alim_mondiale

743700000.0

In [46]:
# pourcentage de la population mondiale sous-alimentée
pop_sous_alim_mondiale/population_totale*100

population_en_millier    10.628346
dtype: float64

In [47]:
sous_alim_2013[['Zone', 'pop_sous_alim']].sort_values(by='pop_sous_alim', ascending=False).head(5)

                    Zone  pop_sous_alim
425                 Inde          216.3
200  Chine, continentale          136.6
685             Pakistan           38.1
80            Bangladesh           26.1
310             Éthiopie           25.3

# Établissez la liste des produits (ainsi que leur code) considéré comme des céréales selon la FAO.

# Repérez dans vos données les informations concernant les céréales (par exemple en créant une colonne de type booléen nommée "is_cereal").

In [48]:
cereales = pd.read_csv('fr_céréales.csv', sep=',')
# chine à enlever 
cereales = cereales.assign(is_cereal = True)
cereales

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,is_cereal
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2511,Blé,2013,2013,Milliers de tonnes,5169,S,Données standardisées,True
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2805,Riz (Eq Blanchi),2013,2013,Milliers de tonnes,342,S,Données standardisées,True
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2513,Orge,2013,2013,Milliers de tonnes,514,S,Données standardisées,True
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,312,S,Données standardisées,True
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,13,S,Données standardisées,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2514,Maïs,2013,2013,Milliers de tonnes,799,S,Données standardisées,True
887,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2516,Avoine,2013,2013,Milliers de tonnes,1,S,Données standardisées,True
888,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2517,Millet,2013,2013,Milliers de tonnes,55,S,Données standardisées,True
889,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2518,Sorgho,2013,2013,Milliers de tonnes,69,S,Données standardisées,True
890,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,181,Zimbabwe,5511,Production,2520,"Céréales, Autres",2013,2013,Milliers de tonnes,2,S,Données standardisées,True

# Question 11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?

In [49]:
nour_anim = vegetaux[vegetaux['Élément'] == 'Aliments pour animaux']
produits_cereales_code = [i for i in cereales['Code Produit']]
nour_anim = nour_anim[nour_anim["Code Produit"].isin(produits_cereales_code)]
nour_anim = nour_anim.assign(valeur_nour_anim = nour_anim['Valeur']*1000*1000)
#nour_anim = nour_anim[nour_anim['valeur_nour_anim']>0]
nour_anim_somme = nour_anim['valeur_nour_anim'].sum()
nour_anim_somme

873535000000.0

In [50]:
nour = animaux_vegetaux[animaux_vegetaux.Élément =='Nourriture']
nour = nour[nour["Code Produit"].isin(produits_cereales_code)]

nour = nour.assign(valeur_nour = nour['Valeur']*1000*1000)
#nour = nour[nour['valeur_nour']>0]
nour_somme = nour['valeur_nour'].sum()
nour_somme

1029010000000.0

In [51]:
# proportion (en termes de poids) est destinée à l'alimentation animale
nour_anim_totale = nour_anim_somme + nour_somme
nour_anim_somme/nour_anim_totale*100

45.91402568664604

In [52]:
# proportion (en termes de poids) est destinée à la nourriture
nour_somme/nour_anim_totale*100

54.08597431335396

# Sélectionnez parmi les données des bilans alimentaires les informations relatives aux pays dans lesquels la FAO recense des personnes en sous-nutrition.
# Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné)
# Groupez ces importations par produit, afin d'avoir une table contenant 1 ligne pour chacun des 15 produits. Ensuite, calculez pour chaque produit les 2 quantités suivantes :

# le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.

# le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

In [53]:
# Pivoter la table selon l'axe Élément
animaux_vegetaux = pd.pivot_table(animaux_vegetaux, values='Valeur', index=['Code zone', 'Zone', 'Code Produit', 'Produit', 'Année', 'source'], columns='Élément', aggfunc=np.sum)
animaux_vegetaux = animaux_vegetaux.reset_index()
animaux_vegetaux

Élément,Code zone,Zone,Code Produit,Produit,Année,source,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),...,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,1,Arménie,2511,Blé,2013,végétale,93.0,0.0,1024.0,130.60,...,30.52,554.0,1.0,361.0,389.0,32.0,312.0,30.0,10.0,-118.0
1,1,Arménie,2513,Orge,2013,végétale,137.0,26.0,0.0,0.00,...,0.00,198.0,0.0,9.0,0.0,15.0,189.0,14.0,7.0,0.0
2,1,Arménie,2514,Maïs,2013,végétale,96.0,NaN,0.0,0.03,...,0.01,102.0,NaN,82.0,0.0,7.0,21.0,0.0,NaN,NaN
3,1,Arménie,2515,Seigle,2013,végétale,1.0,NaN,1.0,0.12,...,0.02,1.0,NaN,0.0,0.0,0.0,1.0,0.0,NaN,0.0
4,1,Arménie,2516,Avoine,2013,végétale,4.0,NaN,2.0,0.37,...,0.09,6.0,NaN,1.0,1.0,0.0,5.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,276,Soudan,2763,Poissons Pelagiques,2013,animale,NaN,0.0,0.0,0.00,...,0.00,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN
15601,276,Soudan,2764,"Poissons Marins, Autres",2013,animale,NaN,0.0,0.0,0.13,...,0.04,5.0,NaN,NaN,5.0,NaN,5.0,NaN,NaN,NaN
15602,276,Soudan,2805,Riz (Eq Blanchi),2013,végétale,NaN,NaN,14.0,1.27,...,0.28,49.0,NaN,33.0,48.0,NaN,17.0,1.0,NaN,0.0
15603,276,Soudan,2848,Lait - Excl Beurre,2013,animale,NaN,0.0,315.0,155.20,...,15.75,5892.0,0.0,232.0,5892.0,NaN,5660.0,NaN,0.0,NaN
15604,276,Soudan,2899,Miscellanees,2013,végétale,NaN,NaN,7.0,NaN,...,1.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
population_sans_chine.rename(columns={'Zone': 'zone', 'population_en_millier': 'population'}, inplace = True)
population_sans_chine

C:\ProgramData\Anaconda3.2020.07\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

                                       zone  population
0                               Afghanistan    30552000
1                            Afrique du Sud    52776000
2                                   Albanie     3173000
3                                   Algérie    39208000
4                                 Allemagne    82727000
..                                      ...         ...
170  Venezuela (République bolivarienne du)    30405000
171                                Viet Nam    91680000
172                                   Yémen    24407000
173                                  Zambie    14539000
174                                Zimbabwe    14150000

[174 rows x 2 columns]

In [55]:
# "Sécurité alimentaire" columns
sa_columns = ['Code zone', 'Zone', 'Élément', 'Produit', 'Année', 'Valeur']

sousalimentation = pd.read_csv("fr_sousalimentation.csv")[sa_columns]

sousalimentation.rename(
    columns={
        'Code zone': 'code_zone',
        'Zone': 'zone',
        'Valeur': 'pop_sous_alim',
        'Année': 'annee'
    },
    inplace=True
)

def year_format(year_code):
    """ From year_code format (XXXXXXX) to standard year format (XXXX) """
    
    if year_code == '2011-2013':
        return 2012

    elif year_code == '2012-2014':
        return 2013
    
    elif year_code == '2013-2015':
        return 2014
    
    elif year_code == '2014-2016':
        return 2015
    
    elif year_code == '2015-2017':
        return 2016
    
    elif year_code == '2016-2018':
        return 2017

# Apply the standard year format XXXX
sousalimentation['annee'] = sousalimentation['annee'].apply(year_format)

sousalimentation.fillna(0, inplace=True)
sousalimentation['pop_sous_alim'] = pd.to_numeric(sousalimentation['pop_sous_alim'], errors='coerce')

sousalimentation = sousalimentation.assign(pop_sous_alim =  sousalimentation['pop_sous_alim']* 1000000)


# Enlever "China" (We just keep the China sub-countries)
sousalimentation = sousalimentation[sousalimentation.zone != 'Chine'].copy()

# sousalimentaion en 2013
sousalimentation_2013 = sousalimentation[sousalimentation.annee == 2013]

sousalimentation_2013.head(5)

,code_zone,zone,Élément,Produit,annee,pop_sous_alim
0,2,Afghanistan,Valeur,Nombre de personnes sous-alimentées (millions)...,2013,7900000.0
5,202,Afrique du Sud,Valeur,Nombre de personnes sous-alimentées (millions)...,2013,2600000.0
10,3,Albanie,Valeur,Nombre de personnes sous-alimentées (millions)...,2013,200000.0
15,4,Algérie,Valeur,Nombre de personnes sous-alimentées (millions)...,2013,1700000.0
20,79,Allemagne,Valeur,Nombre de personnes sous-alimentées (millions)...,2013,0.0

In [56]:
# Rename
animaux_vegetaux.rename(columns={
    'Code zone': 'code_zone',
    'Zone': 'zone',
    'Code Produit': 'code_produit',
    'Produit': 'produit',
    'Année': 'annee',
    'source' : 'origin',
    'Aliments pour animaux': 'alim_anim',
    'Autres utilisations (non alimentaire)': 'autre_util',
    'Disponibilité alimentaire (Kcal/personne/jour)': 'dispo_alim_kcal',
    'Disponibilité alimentaire en quantité (kg/personne/an)': 'dispo_alim_quantite',
    'Disponibilité de matière grasse en quantité (g/personne/jour)': 'dispo_alim_grasse',
    'Disponibilité de protéines en quantité (g/personne/jour)': 'dispo_prot',
    'Exportations - Quantité': 'exportation',
    'Importations - Quantité': 'importation',
    'Nourriture': 'nour',
    'Pertes': 'perte',
    'Production': 'production',
    'Semences': 'semence',
    'Traitement': 'traitement',
    'Variation de stock': 'variation_stock',
    'Disponibilité intérieure': 'dispo_int'
}, inplace=True)

# Left join with the population size
animaux_vegetaux = animaux_vegetaux.merge(population_sans_chine, how='left', on='zone')

# Clean
animaux_vegetaux.fillna(0, inplace=True)

# From 1000 tons to kg
animaux_vegetaux['exportation'] = animaux_vegetaux['exportation'] * 1000000
animaux_vegetaux['autre_util'] = animaux_vegetaux['autre_util'] * 1000000
animaux_vegetaux['alim_anim'] = animaux_vegetaux['alim_anim'] * 1000000
animaux_vegetaux['importation'] = animaux_vegetaux['importation'] * 1000000
animaux_vegetaux['nour'] = animaux_vegetaux['nour'] * 1000000
animaux_vegetaux['perte'] = animaux_vegetaux['perte'] * 1000000
animaux_vegetaux['production'] = animaux_vegetaux['production'] * 1000000
animaux_vegetaux['semence'] = animaux_vegetaux['semence'] * 1000000
animaux_vegetaux['traitement'] = animaux_vegetaux['traitement'] * 1000000
animaux_vegetaux['variation_stock'] = animaux_vegetaux['variation_stock'] * 1000000
animaux_vegetaux['dispo_int'] = animaux_vegetaux['dispo_int'] * 1000000
animaux_vegetaux.head(10)

,code_zone,zone,code_produit,produit,annee,origin,alim_anim,autre_util,dispo_alim_kcal,dispo_alim_quantite,...,dispo_int,exportation,importation,nour,perte,production,semence,traitement,variation_stock,population
0,1,Arménie,2511,Blé,2013,végétale,93000000.0,0.0,1024.0,130.60,...,554000000.0,1000000.0,361000000.0,389000000.0,32000000.0,312000000.0,30000000.0,10000000.0,-118000000.0,2977000
1,1,Arménie,2513,Orge,2013,végétale,137000000.0,26000000.0,0.0,0.00,...,198000000.0,0.0,9000000.0,0.0,15000000.0,189000000.0,14000000.0,7000000.0,0.0,2977000
2,1,Arménie,2514,Maïs,2013,végétale,96000000.0,0.0,0.0,0.03,...,102000000.0,0.0,82000000.0,0.0,7000000.0,21000000.0,0.0,0.0,0.0,2977000
3,1,Arménie,2515,Seigle,2013,végétale,1000000.0,0.0,1.0,0.12,...,1000000.0,0.0,0.0,0.0,0.0,1000000.0,0.0,0.0,0.0,2977000
4,1,Arménie,2516,Avoine,2013,végétale,4000000.0,0.0,2.0,0.37,...,6000000.0,0.0,1000000.0,1000000.0,0.0,5000000.0,0.0,0.0,0.0,2977000
5,1,Arménie,2517,Millet,2013,végétale,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000
6,1,Arménie,2518,Sorgho,2013,végétale,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000
7,1,Arménie,2520,"Céréales, Autres",2013,végétale,1000000.0,12000000.0,14.0,1.96,...,21000000.0,0.0,4000000.0,6000000.0,1000000.0,17000000.0,1000000.0,0.0,0.0,2977000
8,1,Arménie,2531,Pommes de Terre,2013,végétale,225000000.0,16000000.0,82.0,45.10,...,672000000.0,9000000.0,5000000.0,134000000.0,96000000.0,661000000.0,123000000.0,78000000.0,15000000.0,2977000
9,1,Arménie,2532,Manioc,2013,végétale,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000

In [57]:
animaux_vegetaux['dispo_alim_kcal_p_j'] = animaux_vegetaux['dispo_alim_kcal']
animaux_vegetaux['dispo_prot_p_j'] = animaux_vegetaux['dispo_prot']

animaux_vegetaux['dispo_alim_kcal'] = animaux_vegetaux['dispo_alim_kcal'] * animaux_vegetaux['population']
animaux_vegetaux['dispo_prot'] = animaux_vegetaux['dispo_prot'] * animaux_vegetaux['population']

animaux_vegetaux['dispo_alim_kcal'].fillna(0, inplace=True)
animaux_vegetaux['dispo_prot'].fillna(0, inplace=True)

display(animaux_vegetaux.head(10))

,code_zone,zone,code_produit,produit,annee,origin,alim_anim,autre_util,dispo_alim_kcal,dispo_alim_quantite,...,importation,nour,perte,production,semence,traitement,variation_stock,population,dispo_alim_kcal_p_j,dispo_prot_p_j
0,1,Arménie,2511,Blé,2013,végétale,93000000.0,0.0,3.048448e+09,130.60,...,361000000.0,389000000.0,32000000.0,312000000.0,30000000.0,10000000.0,-118000000.0,2977000,1024.0,30.52
1,1,Arménie,2513,Orge,2013,végétale,137000000.0,26000000.0,0.000000e+00,0.00,...,9000000.0,0.0,15000000.0,189000000.0,14000000.0,7000000.0,0.0,2977000,0.0,0.00
2,1,Arménie,2514,Maïs,2013,végétale,96000000.0,0.0,0.000000e+00,0.03,...,82000000.0,0.0,7000000.0,21000000.0,0.0,0.0,0.0,2977000,0.0,0.01
3,1,Arménie,2515,Seigle,2013,végétale,1000000.0,0.0,2.977000e+06,0.12,...,0.0,0.0,0.0,1000000.0,0.0,0.0,0.0,2977000,1.0,0.02
4,1,Arménie,2516,Avoine,2013,végétale,4000000.0,0.0,5.954000e+06,0.37,...,1000000.0,1000000.0,0.0,5000000.0,0.0,0.0,0.0,2977000,2.0,0.09
5,1,Arménie,2517,Millet,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00
6,1,Arménie,2518,Sorgho,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00
7,1,Arménie,2520,"Céréales, Autres",2013,végétale,1000000.0,12000000.0,4.167800e+07,1.96,...,4000000.0,6000000.0,1000000.0,17000000.0,1000000.0,0.0,0.0,2977000,14.0,0.39
8,1,Arménie,2531,Pommes de Terre,2013,végétale,225000000.0,16000000.0,2.441140e+08,45.10,...,5000000.0,134000000.0,96000000.0,661000000.0,123000000.0,78000000.0,15000000.0,2977000,82.0,1.94
9,1,Arménie,2532,Manioc,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00

In [58]:
# ajouter la colonne "est_sousalimente" au principal dataframe

temp_df = pd.DataFrame(sousalimentation_2013, columns=['code_zone', 'sousalimentation', 'est_sousalimente'])
animaux_vegetaux = animaux_vegetaux.merge(temp_df, how='left', on='code_zone')
animaux_vegetaux.head(50)

,code_zone,zone,code_produit,produit,annee,origin,alim_anim,autre_util,dispo_alim_kcal,dispo_alim_quantite,...,perte,production,semence,traitement,variation_stock,population,dispo_alim_kcal_p_j,dispo_prot_p_j,sousalimentation,est_sousalimente
0,1,Arménie,2511,Blé,2013,végétale,93000000.0,0.0,3.048448e+09,130.60,...,32000000.0,312000000.0,30000000.0,10000000.0,-118000000.0,2977000,1024.0,30.52,NaN,NaN
1,1,Arménie,2513,Orge,2013,végétale,137000000.0,26000000.0,0.000000e+00,0.00,...,15000000.0,189000000.0,14000000.0,7000000.0,0.0,2977000,0.0,0.00,NaN,NaN
2,1,Arménie,2514,Maïs,2013,végétale,96000000.0,0.0,0.000000e+00,0.03,...,7000000.0,21000000.0,0.0,0.0,0.0,2977000,0.0,0.01,NaN,NaN
3,1,Arménie,2515,Seigle,2013,végétale,1000000.0,0.0,2.977000e+06,0.12,...,0.0,1000000.0,0.0,0.0,0.0,2977000,1.0,0.02,NaN,NaN
4,1,Arménie,2516,Avoine,2013,végétale,4000000.0,0.0,5.954000e+06,0.37,...,0.0,5000000.0,0.0,0.0,0.0,2977000,2.0,0.09,NaN,NaN
5,1,Arménie,2517,Millet,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
6,1,Arménie,2518,Sorgho,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
7,1,Arménie,2520,"Céréales, Autres",2013,végétale,1000000.0,12000000.0,4.167800e+07,1.96,...,1000000.0,17000000.0,1000000.0,0.0,0.0,2977000,14.0,0.39,NaN,NaN
8,1,Arménie,2531,Pommes de Terre,2013,végétale,225000000.0,16000000.0,2.441140e+08,45.10,...,96000000.0,661000000.0,123000000.0,78000000.0,15000000.0,2977000,82.0,1.94,NaN,NaN
9,1,Arménie,2532,Manioc,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
10,1,Arménie,2534,Racines nda,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
11,1,Arménie,2537,"Sucre, betterave",2013,végétale,1000000.0,0.0,0.000000e+00,0.00,...,0.0,55000000.0,0.0,54000000.0,0.0,2977000,0.0,0.00,NaN,NaN
12,1,Arménie,2542,Sucre Eq Brut,2013,végétale,0.0,0.0,8.990540e+08,33.03,...,0.0,8000000.0,0.0,0.0,3000000.0,2977000,302.0,0.00,NaN,NaN
13,1,Arménie,2543,Edulcorants Autres,2013,végétale,0.0,0.0,5.358600e+07,1.82,...,0.0,2000000.0,0.0,0.0,2000000.0,2977000,18.0,0.00,NaN,NaN
14,1,Arménie,2546,Haricots,2013,végétale,5000000.0,0.0,0.000000e+00,0.00,...,0.0,5000000.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
15,1,Arménie,2547,Pois,2013,végétale,2000000.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
16,1,Arménie,2549,Légumineuses Autres,2013,végétale,3000000.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
17,1,Arménie,2551,Noix,2013,végétale,0.0,0.0,5.358600e+07,2.15,...,0.0,5000000.0,0.0,0.0,0.0,2977000,18.0,0.42,NaN,NaN
18,1,Arménie,2555,Soja,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
19,1,Arménie,2556,Arachides Decortiquees,2013,végétale,0.0,0.0,1.786200e+07,0.40,...,0.0,0.0,0.0,0.0,0.0,2977000,6.0,0.29,NaN,NaN
20,1,Arménie,2557,Graines de tournesol,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,2000000.0,0.0,2977000,0.0,0.00,NaN,NaN
21,1,Arménie,2558,Graines Colza/Moutarde,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
22,1,Arménie,2560,Coco (Incl Coprah),2013,végétale,0.0,0.0,0.000000e+00,0.08,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
23,1,Arménie,2561,Sésame,2013,végétale,0.0,0.0,0.000000e+00,0.01,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
24,1,Arménie,2563,Olives,2013,végétale,0.0,0.0,8.931000e+06,0.92,...,0.0,0.0,0.0,0.0,0.0,2977000,3.0,0.03,NaN,NaN
25,1,Arménie,2570,"Plantes Oleiferes, Autre",2013,végétale,1000000.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
26,1,Arménie,2571,Huile de Soja,2013,végétale,0.0,0.0,1.190800e+07,0.18,...,0.0,0.0,0.0,0.0,0.0,2977000,4.0,0.00,NaN,NaN
27,1,Arménie,2572,Huile d'Arachide,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
28,1,Arménie,2573,Huile de Tournesol,2013,végétale,0.0,3000000.0,6.430320e+08,8.85,...,0.0,1000000.0,0.0,0.0,0.0,2977000,216.0,0.04,NaN,NaN
29,1,Arménie,2574,Huile de Colza&Moutarde,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
30,1,Arménie,2575,Huile Graines de Coton,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
31,1,Arménie,2576,Huile de Palmistes,2013,végétale,0.0,0.0,0.000000e+00,0.01,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
32,1,Arménie,2577,Huile de Palme,2013,végétale,0.0,1000000.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
33,1,Arménie,2578,Huile de Coco,2013,végétale,0.0,0.0,2.083900e+07,0.30,...,0.0,0.0,0.0,0.0,0.0,2977000,7.0,0.00,NaN,NaN
34,1,Arménie,2579,Huile de Sésame,2013,végétale,0.0,0.0,0.000000e+00,0.00,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
35,1,Arménie,2580,Huile d'Olive,2013,végétale,0.0,0.0,2.977000e+06,0.03,...,0.0,0.0,0.0,0.0,0.0,2977000,1.0,0.00,NaN,NaN
36,1,Arménie,2582,Huile de Germe de Maïs,2013,végétale,0.0,0.0,8.931000e+06,0.14,...,0.0,0.0,0.0,0.0,0.0,2977000,3.0,0.00,NaN,NaN
37,1,Arménie,2586,Huil Plantes Oleif Autr,2013,végétale,0.0,2000000.0,0.000000e+00,0.01,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
38,1,Arménie,2601,Tomates,2013,végétale,0.0,0.0,1.220570e+08,88.10,...,11000000.0,276000000.0,0.0,0.0,0.0,2977000,41.0,1.94,NaN,NaN
39,1,Arménie,2602,Oignons,2013,végétale,0.0,0.0,4.465500e+07,17.57,...,0.0,45000000.0,0.0,0.0,0.0,2977000,15.0,0.53,NaN,NaN
40,1,Arménie,2605,"Légumes, Autres",2013,végétale,13000000.0,0.0,4.257110e+08,243.22,...,27000000.0,764000000.0,0.0,0.0,0.0,2977000,143.0,6.66,NaN,NaN
41,1,Arménie,2611,"Oranges, Mandarines",2013,végétale,0.0,0.0,1.190800e+07,4.78,...,0.0,0.0,0.0,0.0,0.0,2977000,4.0,0.07,NaN,NaN
42,1,Arménie,2612,Citrons & Limes,2013,végétale,0.0,0.0,0.000000e+00,0.31,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.01,NaN,NaN
43,1,Arménie,2613,Pamplemousse,2013,végétale,0.0,0.0,0.000000e+00,0.52,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
44,1,Arménie,2614,"Agrumes, Autres",2013,végétale,0.0,0.0,0.000000e+00,0.46,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.01,NaN,NaN
45,1,Arménie,2615,Bananes,2013,végétale,0.0,0.0,2.977000e+06,0.77,...,0.0,0.0,0.0,0.0,0.0,2977000,1.0,0.01,NaN,NaN
46,1,Arménie,2616,Bananes plantains,2013,végétale,0.0,0.0,1.488500e+07,2.55,...,0.0,0.0,0.0,0.0,0.0,2977000,5.0,0.06,NaN,NaN
47,1,Arménie,2617,Pommes,2013,végétale,19000000.0,0.0,9.824100e+07,24.79,...,8000000.0,112000000.0,0.0,7000000.0,0.0,2977000,33.0,0.08,NaN,NaN
48,1,Arménie,2618,Ananas,2013,végétale,0.0,0.0,0.000000e+00,0.16,...,0.0,0.0,0.0,0.0,0.0,2977000,0.0,0.00,NaN,NaN
49,1,Arménie,2619,Dattes,2013,végétale,0.0,0.0,2.977000e+06,0.15,...,0.0,0.0,0.0,0.0,0.0,2977000,1.0,0.01,NaN,NaN

In [59]:
# Dataframe with just undernourishment countries
animaux_vegetaux_11 = animaux_vegetaux[animaux_vegetaux['est_sousalimente'] == True].copy()

# Top 15 Export products
top_export_products = animaux_vegetaux.sort_values(by='exportation', ascending=False)[['code_produit', 'produit']].drop_duplicates()[0:15]
top_export_products_name = [x for x in top_export_products['produit']]
top_export_products_code = [x for x in top_export_products['code_produit']]

# Print them
print(""" Les 15 produits les plus exportés par les pays qui ont la plus grande population sousalimentée:

""")
for i, produit in enumerate(top_export_products_name):
    print(f"{i+1} - {produit}")

 Les 15 produits les plus exportés par les pays qui ont la plus grande population sousalimentée:


1 - Soja
2 - Blé
3 - Sucre Eq Brut
4 - Maïs
5 - Manioc
6 - Huile de Palme
7 - Lait - Excl Beurre
8 - Oranges, Mandarines
9 - Riz (Eq Blanchi)
10 - Orge
11 - Légumes, Autres
12 - Graines Colza/Moutarde
13 - Pommes de Terre
14 - Bananes
15 - Poissons Pelagiques

In [60]:

# 200 produits les plus importés par les pays les plus sous-alimentés
top_import_of_poor_exports = animaux_vegetaux.loc[(animaux_vegetaux['code_produit'].isin(top_export_products_code)), :]

top_import_of_poor_exports = top_import_of_poor_exports.sort_values(by='importation', ascending=False)[0:200]

final_columns = ['code_produit', 'produit', 'alim_anim', 'autre_util', 'dispo_int', 'nour']
df_200 = top_import_of_poor_exports[final_columns].copy()
#df_q11 = animaux_vegetaux[final_columns].copy()
df_200 = df_200.groupby(['code_produit', 'produit']).sum()
df_200.reset_index(inplace=True)
top_import_of_poor_exports

,code_zone,zone,code_produit,produit,annee,origin,alim_anim,autre_util,dispo_alim_kcal,dispo_alim_quantite,...,perte,production,semence,traitement,variation_stock,population,dispo_alim_kcal_p_j,dispo_prot_p_j,sousalimentation,est_sousalimente
2509,41,"Chine, continentale",2555,Soja,2013,végétale,9.530000e+09,0.000000e+00,4.849484e+10,3.66,...,6.040000e+08,1.195100e+10,713000000.0,5.916200e+10,0.0,1385567000,35.0,3.29,NaN,NaN
2496,41,"Chine, continentale",2532,Manioc,2013,végétale,2.286800e+10,7.940000e+09,8.313402e+09,1.91,...,1.380000e+08,4.585000e+09,0.0,0.000000e+00,0.0,1385567000,6.0,0.05,NaN,NaN
6965,110,Japon,2514,Maïs,2013,végétale,1.096400e+10,2.880000e+08,7.755784e+09,9.21,...,3.000000e+06,0.000000e+00,0.0,2.235000e+09,259000000.0,127144000,61.0,0.16,NaN,NaN
12012,194,Arabie saoudite,2513,Orge,2013,végétale,1.000000e+10,0.000000e+00,0.000000e+00,0.01,...,3.170000e+08,1.100000e+07,0.0,0.000000e+00,-241000000.0,28829000,0.0,0.00,NaN,NaN
3674,59,Égypte,2511,Blé,2013,végétale,4.860000e+09,0.000000e+00,9.641580e+10,146.83,...,2.224000e+09,9.460000e+09,217000000.0,0.000000e+00,-260000000.0,82056000,1175.0,35.62,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12195,195,Sénégal,2805,Riz (Eq Blanchi),2013,végétale,0.000000e+00,6.300000e+07,1.010510e+10,72.29,...,1.800000e+07,2.910000e+08,6000000.0,1.000000e+06,-214000000.0,14133000,715.0,14.41,NaN,NaN
7509,117,République de Corée,2555,Soja,2013,végétale,3.000000e+07,0.000000e+00,3.251358e+09,8.35,...,8.000000e+06,1.540000e+08,4000000.0,8.140000e+08,0.0,49263000,66.0,6.05,NaN,NaN
7534,117,République de Corée,2605,"Légumes, Autres",2013,végétale,0.000000e+00,0.000000e+00,6.896820e+09,172.38,...,1.273000e+09,8.753000e+09,0.0,0.000000e+00,0.0,49263000,140.0,7.30,NaN,NaN
6137,101,Indonésie,2532,Manioc,2013,végétale,4.800000e+08,8.894000e+09,3.298231e+10,46.97,...,3.110000e+09,2.393700e+10,0.0,0.000000e+00,0.0,249866000,132.0,0.70,NaN,NaN
7240,114,Kenya,2511,Blé,2013,végétale,0.000000e+00,3.400000e+07,1.144333e+10,34.65,...,3.100000e+07,4.860000e+08,11000000.0,0.000000e+00,50000000.0,44354000,258.0,7.73,NaN,NaN

In [61]:
# calculons les 2 ratios 

df_200['autre_sur_dispo'] = df_200['autre_util'] / df_200['dispo_int']
df_200['nour_sur_nour_anim'] = df_200['alim_anim'] / (df_200['alim_anim'] + df_200['nour'])

df_200.sort_values(by='nour_sur_nour_anim', ascending=False, inplace=True)

display(df_200)

,code_produit,produit,alim_anim,autre_util,dispo_int,nour,autre_sur_dispo,nour_sur_nour_anim
7,2558,Graines Colza/Moutarde,4.143000e+09,9.100000e+07,3.750500e+10,5.900000e+07,0.002426,0.985959
1,2513,Orge,2.015300e+10,1.200000e+07,2.947300e+10,3.380000e+08,0.000407,0.983505
2,2514,Maïs,3.921620e+11,1.818680e+11,6.877850e+11,5.525100e+10,0.264426,0.876510
12,2763,Poissons Pelagiques,1.215600e+10,0.000000e+00,1.609400e+10,3.937000e+09,0.000000,0.755359
6,2555,Soja,1.371000e+10,5.240000e+08,1.595700e+11,7.510000e+09,0.003284,0.646089
4,2532,Manioc,2.514900e+10,2.035500e+10,6.732600e+10,1.525700e+10,0.302335,0.622408
0,2511,Blé,9.550300e+10,1.439700e+10,4.479420e+11,2.966120e+11,0.032140,0.243559
13,2805,Riz (Eq Blanchi),1.259200e+10,2.533000e+09,1.473520e+11,1.204170e+11,0.017190,0.094670
14,2848,Lait - Excl Beurre,2.721100e+10,1.233700e+10,3.411180e+11,2.988430e+11,0.036166,0.083456
3,2531,Pommes de Terre,1.974000e+09,3.427000e+09,5.251900e+10,3.943500e+10,0.065253,0.047671
9,2605,"Légumes, Autres",3.428000e+09,0.000000e+00,7.970800e+10,6.983000e+10,0.000000,0.046794
5,2542,Sucre Eq Brut,0.000000e+00,2.996000e+09,7.845300e+10,6.497100e+10,0.038188,0.000000
8,2577,Huile de Palme,0.000000e+00,1.856800e+10,2.561800e+10,6.833000e+09,0.724803,0.000000
10,2611,"Oranges, Mandarines",0.000000e+00,1.000000e+06,1.953400e+10,1.919200e+10,0.000051,0.000000
11,2615,Bananes,0.000000e+00,0.000000e+00,7.466000e+09,7.123000e+09,0.000000,0.000000

# Question 12 : Donnez les 3 produits qui on t la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)

In [62]:
df_200 = df_200.sort_values(by=['autre_sur_dispo'], ascending=False)
df_200[['code_produit', 'produit', 'autre_sur_dispo','nour_sur_nour_anim']]

    code_produit                 produit  autre_sur_dispo  nour_sur_nour_anim
8           2577          Huile de Palme         0.724803            0.000000
4           2532                  Manioc         0.302335            0.622408
2           2514                    Maïs         0.264426            0.876510
3           2531         Pommes de Terre         0.065253            0.047671
5           2542           Sucre Eq Brut         0.038188            0.000000
14          2848      Lait - Excl Beurre         0.036166            0.083456
0           2511                     Blé         0.032140            0.243559
13          2805        Riz (Eq Blanchi)         0.017190            0.094670
6           2555                    Soja         0.003284            0.646089
7           2558  Graines Colza/Moutarde         0.002426            0.985959
1           2513                    Orge         0.000407            0.983505
10          2611     Oranges, Mandarines         0.000051            0.000000
12          2763     Poissons Pelagiques         0.000000            0.755359
9           2605         Légumes, Autres         0.000000            0.046794
11          2615                 Bananes         0.000000            0.000000

In [63]:
df_200 = df_200.sort_values(by=['nour_sur_nour_anim'], ascending=False)

df_200[[ 'code_produit', 'produit', 'autre_sur_dispo', 'nour_sur_nour_anim' ]].head(3)

   code_produit                 produit  autre_sur_dispo  nour_sur_nour_anim
7          2558  Graines Colza/Moutarde         0.002426            0.985959
1          2513                    Orge         0.000407            0.983505
2          2514                    Maïs         0.264426            0.876510

In [64]:
df_200 = df_200.sort_values(by=['autre_sur_dispo'], ascending=False).head(3)
df_200[[ 'code_produit', 'produit', 'autre_sur_dispo', 'nour_sur_nour_anim' ]].head(3)

   code_produit         produit  autre_sur_dispo  nour_sur_nour_anim
8          2577  Huile de Palme         0.724803            0.000000
4          2532          Manioc         0.302335            0.622408
2          2514            Maïs         0.264426            0.876510

# Question 13 : Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?

In [65]:
# Quantité de cereales qui pourraient etre libérées si les USA diminuaient 10% de leur production 
# de produits animaux
nour_anim_usa = nour_anim[nour_anim.Zone == "États-Unis d'Amérique"]
nour_anim_usa = nour_anim_usa['valeur_nour_anim'].sum()*0.1/1000
nour_anim_usa

14009600.0

# Question 14 : En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?

In [66]:
vegetaux_thai = vegetaux[(vegetaux.Zone == 'Thaïlande')]
vegetaux_thai = vegetaux_thai[vegetaux_thai.Élément ==  'Exportations - Quantité']
vegetaux_thai_export = vegetaux_thai[['Zone', 'Produit', 'Valeur']]
vegetaux_thai_export

            Zone                 Produit  Valeur
96306  Thaïlande                     Blé   237.0
96319  Thaïlande        Riz (Eq Blanchi)  6860.0
96333  Thaïlande                    Orge     0.0
96345  Thaïlande                    Maïs   591.0
96357  Thaïlande                  Seigle     0.0
...          ...                     ...     ...
96954  Thaïlande                   Bière   249.0
96963  Thaïlande      Boissons Fermentés     2.0
96972  Thaïlande    Boissons Alcooliques    13.0
96980  Thaïlande  Alcool, non Comestible   110.0
96984  Thaïlande   Aliments pour enfants     7.0

[71 rows x 3 columns]

In [67]:
# manioc expporté 
thai_manioc_export = vegetaux_thai_export[vegetaux_thai_export.Produit ==  'Manioc']
thai_manioc_export = (thai_manioc_export['Valeur']*1000*1000).sum()
#thai_manioc_export = pd.to_numeric(thai_manioc_export['Valeur'])
thai_manioc_export

25214000000.0

In [68]:
# pourcentage de manioc exporté par la Thailande
vegetaux_thai = vegetaux[(vegetaux.Zone == 'Thaïlande')]
vegetaux_thai = vegetaux_thai[vegetaux_thai.Élément ==  'Production']
vegetaux_thai = vegetaux_thai[vegetaux_thai.Produit ==  'Manioc']
vegetaux_thai_produits = (vegetaux_thai['Valeur']*1000*1000).sum()
percent_manioc_exporte = thai_manioc_export/vegetaux_thai_produits
percent_manioc_exporte*100

83.41272991928014

In [69]:
# population thailandaise
pop_thai = population_sans_chine[population_sans_chine.zone == 'Thaïlande']
pop_thai = pop_thai['population'].sum()
pop_thai

67011000

In [70]:
# population thailandaise sous-alimentée
sous_alim_thai = sous_alim_2013[sous_alim_2013.Zone == 'Thaïlande']
sous_alim_thai = (sous_alim_thai['pop_sous_alim'].sum())*1000000
sous_alim_thai

5600000.0

In [71]:
# pourcentage de personnes sous-alimentées
percent_thai_sous_alim = sous_alim_thai/pop_thai
percent_thai_sous_alim*100

8.356836937219263